import{S as p,i as F}from"./assets/vendor-46aac873.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{const m=document.querySelector(".searchForm"),a=document.querySelector(".searchInput"),i=document.querySelector(".loader"),n=document.querySelector(".gallery"),e="42055816-5ec499474650eadfc6b07a02f",s="https://pixabay.com/api/",l=new p(".gallery a",{captionDelay:250,captionsData:"alt"});m.addEventListener("submit",d=>{d.preventDefault();const c=a.value.trim();if(c===""){F.error({title:"Error",titleColor:"#FFFFFF",message:"Please enter a search term.",messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#EF4040",iconColor:"#FFFFFF",position:"topRight"});return}i.classList.remove("hidden"),n.innerHTML="",fetch(`${s}?key=${e}&q=${c}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(`HTTP error! Status: ${o.status}`);return o.json()}).then(o=>{if(o.hits.length===0)F.warning({title:"",titleColor:"#FFFFFF",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#FFA000",iconColor:"#FFFFFF",position:"center"});else{const t=o.hits.map(r=>({webformatURL:r.webformatURL,largeImageURL:r.largeImageURL,tags:r.tags,likes:r.likes,views:r.views,comments:r.comments,downloads:r.downloads}));u(t)}}).catch(o=>{console.error("Error fetching data:",o),F.error({title:"Error",titleColor:"#FFFFFF",message:"An error occurred while fetching data. Please try again.",messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#EF4040",iconColor:"#FFFFFF",position:"topRight"})}).finally(()=>{i.classList.add("hidden")}),m.reset()});function u(d){const c=d.map((o,t)=>`
        <div class="gallery-item">
          <a href="${o.largeImageURL}" data-lightbox="gallery" data-title="${o.tags}">
            <img src="${o.webformatURL}" alt="${o.tags}" class="image-thumbnail image-${t+1}">
          </a>
          <div class="image-details image-details-${t+1}">
            <p class="likes likes-${t+1}">Likes: <span class="result-likes">${o.likes}</span></p>
            <p class="views views-${t+1}">Views: <span class="result-views">${o.views}</span></p>
            <p class="comments comments-${t+1}">Comments: <span class="result-comments">${o.comments}</span></p>
            <p class="downloads downloads-${t+1}">Downloads: <span class="result-downloads">${o.downloads}</span></p>
          </div>
        </div>
      `).join("");n.innerHTML=c,l.refresh()}});
//# sourceMappingURL=commonHelpers.js.map
